apiVersion: v1
kind: Service
metadata:
  name: now-frontend
  namespace: visionapi
spec:
  selector:
    app: now-frontend
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
